# -*- coding: utf-8 -*-
"""150221np_pd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/noski927/08f43341a7d39f4e49a41ab9eb065888/150221np_pd.ipynb
"""

import numpy as np

df=np.array([[1,6],
            [2,8],
            [3,11],
            [3,10],
            [1,7]])

df.shape

mean_a=np.mean(df[0:,0]),np.mean(df[0:,1])
print(mean_a)

a_centered=df-mean_a # очень длинные формулировка задания я дольше понимал че делать надо, надеюсь что понял)

a_centered_sp= np.dot(a_centered[0:,0],a_centered[0:,1])/(df.shape[0]-1)
print(a_centered_sp)

np.cov(df.T)

import pandas as pd

au={'author_id':[1,2,3],'author_name':['Тургенев', 'Чехов', 'Островский']}
autors=pd.DataFrame(au)

b={'author_id':[1, 1, 1, 2, 2, 3, 3],
'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
'price':[450, 300, 350, 500, 450, 370, 290]}
book=pd.DataFrame(b)

authors_price=autors.merge(book)
authors_price

top5 = authors_price.sort_values(by=['price'],ascending=False).head()

authors_stat=authors_price.groupby('author_name').describe()['price']
authors_stat

c=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price['cover']=c
authors_price
pd.pivot_table(authors_price,columns='cover',index='author_name',fill_value=0)['price']